version: '3.7'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testovich
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: testovich
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        $table_prefix = 'wp_';
        define( 'WP_HOME', 'http://testovich1.test:8000' );
        define( 'WP_SITEURL', 'http://testovich1.test:8000' );
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
